[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dvt"
version = "0.1.0"
description = "Developer helper launcher and manager"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
dvt = "dvt.cli:main"
